# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0004_auto_20161030_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default=b''),
        ),
    ]
