# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0007_auto_20161105_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custrecord',
            name='total_price',
        ),
    ]
