# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0008_remove_custrecord_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cost',
            field=models.FloatField(),
        ),
    ]
