# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0009_auto_20161114_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
