# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0011_menu_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuimage',
            name='name',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
