# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0012_menuimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='custrecord',
            name='comments',
            field=models.TextField(default=b''),
        ),
    ]
