# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0013_custrecord_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_review', to='choose.CustRecord')),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_review', to='choose.Menu')),
            ],
        ),
    ]
