# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0014_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
