# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0014_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuvideo',
            name='name',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuimage',
            name='photo',
            field=models.ImageField(upload_to=b'/menu/'),
        ),
    ]
