# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0015_auto_20161203_2112'),
        ('choose', '0015_review_create_date'),
    ]

    operations = [
    ]
